### ISSUE TITLE
[Suggestion] Change namespace of P4

### ISSUE THREAD

**Issue by marcelinomalmeidan** [TuckerHaydon/MinimumSnap#3]
I don't think that the namespace ```mediation_layer``` for P4 describes well what it does, specially since it can be used in a larger scope (not only for the mediation layer). I would choose something like ```trajectory_smoothing```. No hurry on this, as this is cosmetic.

**Comment by TuckerHaydon** [comment]
Agreed, mediation layer is not appropriate. Ill change the namespace to match the project name: p4

**Comment by TuckerHaydon** [comment]
Changed and pushed.
