### ISSUE TITLE
Option for verbose in OSQP

### ISSUE THREAD

**Issue by marcelinomalmeidan** [TuckerHaydon/MinimumSnap#7]
Currently verbose is always on. I believe that we should have an option parameter on the class ```PolynomialSolver``` such as ```bool verbose``` so we can set it to false.

**Comment by TuckerHaydon** [comment]
So I understand, you want to turn off the OSQP solver output to terminal?

**Comment by marcelinomalmeidan** [comment]
Yes, I will work on the pull request for this, looks like a simple update.

**Comment by TuckerHaydon** [comment]
You want to change verbosity now, but what about future changes? I don't think it's scalable to append new flags to the Options or PathInfo structs every time we want new data.

I think we may want to put an instance of OSQPSettings in the PolynomialSolver::Options structure that then gets passed to the osqp solver at run time. That way, any end user can configure any osqp options in their own executable.

Similarly, we may want to put an instance of OSQPSolution, OSQPInfo, etc in the PathInfo structure. That way the end user can have whatever data they want from OSQP without further changes to P4.

**Comment by marcelinomalmeidan** [comment]
I agree... This is the best solution!

**Comment by TuckerHaydon** [comment]
Would you like to do it, or me?

**Comment by marcelinomalmeidan** [comment]
I can do it!

**Comment by TuckerHaydon** [comment]
Added osqp_settings to the PolynomialSolver::Options structure. Users now have complete and direct access to all osqp settings.
